pom.xml
As per the information on https://github.com/eclipse-ee4j/ee4j/wiki/New-Maven-Coordinates
Resolves https://github.com/eclipse-ee4j/jta-api/issues/6
=> Change the groupId and artifactId

pom.xml
Resolves https://github.com/eclipse-ee4j/jta-api/issues/15
=> Updated to Eclipse EE4J parent

CONTRIBUTING.md, NOTICE.md
Resolves https://github.com/eclipse-ee4j/jta-api/issues/21 on master
=> Updated with the links to the source code and mailing list

api/pom.xml
=> Updated to jakarta.enterprise:jakarta.enterprise.cdi-api:2.0.1

api/pom.xml
remove maven findbugs plugin
Signed-off-by: Markus Stauffer <Markus.Stauffer@gmail.com>
=> GitHub Issue #79: findbugs-maven-plugin in api/pom.xml

api/pom.xml, pom.xml
The changes in the tags: https://github.com/eclipse-ee4j/ee4j/compare/1.0.5...1.0.6
=> Update maven parent to org.eclipse.ee4j:project:1.0.6

api/pom.xml
To resolve https://github.com/eclipse-ee4j/jta-api/issues/71
=> Updated to include the LICENCE.md and NOTICE.md files from the project root

api/pom.xml
Should resolve https://github.com/eclipse-ee4j/jta-api/issues/87
=> Upgrade spec version maven plugin

api/src/main/javadoc/doc-files/EFSL.html, spec/src/main/asciidoc/license-efsl.adoc
https://github.com/eclipse-ee4j/jta-api/issues/95
=> Updated reference to EFSL and to indicate the specification

spec/src/main/asciidoc/Transactions.adoc
Signed-off-by: Vano Beridze <vanuatoo@gmail.com>
=> Issue 103: Corrected JTS spec link, Corrected JDBC reference name

spec/pom.xml, spec/src/main/asciidoc/Transactions.adoc
Signed-off-by: Rhuan Rocha <rhuan080@gmail.com>
=> Issue 117: Fixing the "Inserting images has a different syntax"

spec/src/main/asciidoc/Transactions.adoc
Signed-off-by: Rhuan Rocha <rhuan080@gmail.com>
Issue 114: Changing internal document linkrefs.
=> Issue 114: Changing internal document linkrefs.

spec/src/main/asciidoc/Transactions.adoc, spec/src/main/asciidoc/transactions-spec.adoc
Signed-off-by: Miguel Serra <Miguel.Serra@criticaltechworks.com>
=> [#109] remove 1.3 version references

spec/src/main/asciidoc/Transactions.adoc
Signed-off-by: Miguel Serra <Miguel.Serra@criticaltechworks.com>
=> [#120] remove javax references

api/pom.xml
Signed-off-by: Scott M Stark <starksm64@gmail.com>
=> Update Automatic-Module-Name to jakarta.transaction, #144

spec/README.md, spec/assembly.xml, spec/pom.xml
https://github.com/eclipse-ee4j/jta-api/issues/112
https://github.com/eclipse-ee4j/jta-api/issues/111
=> Partial revert of dc7915bc787556c8c820ef7f2c0dfd19706eabe7 [#111] [#112]

spec/src/main/asciidoc/Transactions.adoc
Signed-off-by: Miguel Serra <Miguel.Serra@criticaltechworks.com>
=> [#104] Remove JCA reference

spec/src/main/asciidoc/Transactions.adoc
Signed-off-by: Miguel Serra <Miguel.Serra@criticaltechworks.com>
=> [#104] Remove JMS reference

spec/src/main/asciidoc/scope.adoc, spec/src/main/asciidoc/transactions-spec.adoc
Hopefully resolves https://github.com/eclipse-ee4j/jta-api/issues/108
=> Removed the scope statement from Jakarta EE 8

api/src/main/javadoc/doc-files/EFSL.html, spec/src/main/asciidoc/license-efsl.adoc
=> [#95] Revert efsl

api/src/main/java/jakarta/transaction/HeuristicCommitException.java, api/src/main/java/jakarta/transaction/HeuristicMixedException.java, api/src/main/java/jakarta/transaction/HeuristicRollbackException.java, api/src/main/java/jakarta/transaction/InvalidTransactionException.java, api/src/main/java/jakarta/transaction/NotSupportedException.java, api/src/main/java/jakarta/transaction/RollbackException.java, api/src/main/java/jakarta/transaction/Status.java, api/src/main/java/jakarta/transaction/Synchronization.java, api/src/main/java/jakarta/transaction/SystemException.java, api/src/main/java/jakarta/transaction/Transaction.java, api/src/main/java/jakarta/transaction/TransactionManager.java, api/src/main/java/jakarta/transaction/TransactionRequiredException.java, api/src/main/java/jakarta/transaction/TransactionRolledbackException.java, api/src/main/java/jakarta/transaction/TransactionScoped.java, api/src/main/java/jakarta/transaction/TransactionSynchronizationRegistry.java, api/src/main/java/jakarta/transaction/Transactional.java, api/src/main/java/jakarta/transaction/TransactionalException.java, api/src/main/java/jakarta/transaction/UserTransaction.java, api/src/main/java/jakarta/transaction/package.html
Partially address https://github.com/eclipse-ee4j/jta-api/issues/123
=> [#123] Added the version to each API file to render in the javadocs

spec/src/main/asciidoc/Transactions.adoc
Resolves https://github.com/eclipse-ee4j/jta-api/issues/155 (up-to-now)
=> Add a change log for Version 2.0

README.md
To reflect the change in https://github.com/eclipse-ee4j/jta-api/commit/b86a11a62599d6960d28179bdf75f1df89cb81ae
=> [#163] Updated the module name to jakarta.transaction in the readme

spec/src/main/asciidoc/Transactions.adoc
Fix table of contents to match the original document
=> Fix table of contents

spec/src/main/asciidoc/Transactions.adoc
=> Updated the reference to JTS to be the draft 1.0 (rather than 0.95)
